// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    repertoires,
    nodes,
    lines,
    runs,
    moveGrades,
    deviationEvents,
    lineStats,
    plyStats,
    settings,
    syncState,
    appMeta,
    linesByOrdinal,
    runsByLine,
    runsByDay,
    runsBySynced,
    runsDailyStats,
    runsKeyUcis,
  ];
  late final Shape0 repertoires = Shape0(
    source: i0.VersionedTable(
      entityName: 'repertoires',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 nodes = Shape1(
    source: i0.VersionedTable(
      entityName: 'nodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(repertoire_id, node_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 lines = Shape2(
    source: i0.VersionedTable(
      entityName: 'lines',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(repertoire_id, line_key)'],
      columns: [
        _column_13,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 runs = Shape3(
    source: i0.VersionedTable(
      entityName: 'runs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_13,
        _column_29,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 moveGrades = Shape4(
    source: i0.VersionedTable(
      entityName: 'move_grades',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(run_id, ply)'],
      columns: [
        _column_51,
        _column_16,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 deviationEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'deviation_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(run_id)'],
      columns: [
        _column_51,
        _column_16,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 lineStats = Shape6(
    source: i0.VersionedTable(
      entityName: 'line_stats',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(repertoire_id, line_key)'],
      columns: [
        _column_13,
        _column_29,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 plyStats = Shape7(
    source: i0.VersionedTable(
      entityName: 'ply_stats',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(repertoire_id, ucis, ply)'],
      columns: [_column_13, _column_36, _column_16, _column_57, _column_79],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 settings = Shape8(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_80, _column_81],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 syncState = Shape8(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_80, _column_81],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 appMeta = Shape8(
    source: i0.VersionedTable(
      entityName: 'app_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_80, _column_81],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index linesByOrdinal = i1.Index(
    'lines_by_ordinal',
    'CREATE INDEX lines_by_ordinal ON lines (repertoire_id, ordinal)',
  );
  final i1.Index runsByLine = i1.Index(
    'runs_by_line',
    'CREATE INDEX runs_by_line ON runs (repertoire_id, line_key, finished_at)',
  );
  final i1.Index runsByDay = i1.Index(
    'runs_by_day',
    'CREATE INDEX runs_by_day ON runs (local_day)',
  );
  final i1.Index runsBySynced = i1.Index(
    'runs_by_synced',
    'CREATE INDEX runs_by_synced ON runs (synced_at)',
  );
  final i1.Index runsDailyStats = i1.Index(
    'runs_daily_stats',
    'CREATE INDEX runs_daily_stats ON runs (repertoire_id, completed, local_day, graded_count, credit_sum)',
  );
  final i1.Index runsKeyUcis = i1.Index(
    'runs_key_ucis',
    'CREATE INDEX runs_key_ucis ON runs (repertoire_id, line_key, ucis)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pgn =>
      columnsByName['pgn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pgnHash =>
      columnsByName['pgn_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastTrainedAt =>
      columnsByName['last_trained_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get drillStartFrom =>
      columnsByName['drill_start_from']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastMode =>
      columnsByName['last_mode']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pgn',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pgn_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_by',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_trained_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'drill_start_from',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'move1\'',
      defaultValue: const i1.CustomExpression('\'move1\''),
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get repertoireId =>
      columnsByName['repertoire_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get nodeId =>
      columnsByName['node_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get parentId =>
      columnsByName['parent_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ply =>
      columnsByName['ply']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get san =>
      columnsByName['san']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uci =>
      columnsByName['uci']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fen =>
      columnsByName['fen']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isUserMove =>
      columnsByName['is_user_move']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get childIndex =>
      columnsByName['child_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get why =>
      columnsByName['why']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plan =>
      columnsByName['plan']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get watch =>
      columnsByName['watch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alt =>
      columnsByName['alt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get shapes =>
      columnsByName['shapes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rawComment =>
      columnsByName['raw_comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nags =>
      columnsByName['nags']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'repertoire_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'node_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'parent_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ply',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'san',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uci',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fen',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_user_move',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_user_move IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'child_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'why',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plan',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'watch',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'alt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'shapes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'raw_comment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nags',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get repertoireId =>
      columnsByName['repertoire_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lineKey =>
      columnsByName['line_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get leafNodeId =>
      columnsByName['leaf_node_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plies =>
      columnsByName['plies']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userMoveCount =>
      columnsByName['user_move_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get branchPly =>
      columnsByName['branch_ply']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ucis =>
      columnsByName['ucis']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'line_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'leaf_node_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'plies',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'user_move_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'branch_ply',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ucis',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get repertoireId =>
      columnsByName['repertoire_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lineKey =>
      columnsByName['line_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ucis =>
      columnsByName['ucis']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startPly =>
      columnsByName['start_ply']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get wrongMoveMode =>
      columnsByName['wrong_move_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finishedAt =>
      columnsByName['finished_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completed =>
      columnsByName['completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deviated =>
      columnsByName['deviated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get gradedCount =>
      columnsByName['graded_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get creditSum =>
      columnsByName['credit_sum']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get hintCount =>
      columnsByName['hint_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get schema =>
      columnsByName['schema']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_ply',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'wrong_move_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'finished_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (completed IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deviated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (deviated IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'graded_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credit_sum',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hint_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'synced_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schema',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get runId =>
      columnsByName['run_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ply =>
      columnsByName['ply']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get expected =>
      columnsByName['expected']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accepted =>
      columnsByName['accepted']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get firstAttempt =>
      columnsByName['first_attempt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get credit =>
      columnsByName['credit']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hintLevel =>
      columnsByName['hint_level']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get checkCp =>
      columnsByName['check_cp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get checkStatus =>
      columnsByName['check_status']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'run_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'expected',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'accepted',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'first_attempt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'result',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credit',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hint_level',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'check_cp',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'check_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get runId =>
      columnsByName['run_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ply =>
      columnsByName['ply']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deviationUci =>
      columnsByName['deviation_uci']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyUci =>
      columnsByName['reply_uci']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bestUci =>
      columnsByName['best_uci']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lossCp =>
      columnsByName['loss_cp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get passed =>
      columnsByName['passed']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deviation_uci',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reply_uci',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'best_uci',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'loss_cp',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'passed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (passed IN (0, 1))',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get repertoireId =>
      columnsByName['repertoire_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lineKey =>
      columnsByName['line_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archived =>
      columnsByName['archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get runCount =>
      columnsByName['run_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get accuracy =>
      columnsByName['accuracy']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get lastPlayedAt =>
      columnsByName['last_played_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inWeakPool =>
      columnsByName['in_weak_pool']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weakCleanStreak =>
      columnsByName['weak_clean_streak']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get srsState =>
      columnsByName['srs_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get srsReps =>
      columnsByName['srs_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get srsEase =>
      columnsByName['srs_ease']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get srsIntervalDays =>
      columnsByName['srs_interval_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get srsDueDay =>
      columnsByName['srs_due_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get srsLapses =>
      columnsByName['srs_lapses']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get srsFirstSeenDay =>
      columnsByName['srs_first_seen_day']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (archived IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'run_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_68(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'accuracy',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_played_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_weak_pool',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (in_weak_pool IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'weak_clean_streak',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'srs_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'srs_reps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_74(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'srs_ease',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'srs_interval_days',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'srs_due_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'srs_lapses',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'srs_first_seen_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get repertoireId =>
      columnsByName['repertoire_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ucis =>
      columnsByName['ucis']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ply =>
      columnsByName['ply']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get misses =>
      columnsByName['misses']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'misses',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
