import 'package:chess_core/chess_core.dart';
import 'package:test/test.dart';

import 'training_helpers.dart';

// Expected states were generated by an independent Python implementation of
// docs/plan/04-algorithms.md §5.2-5.3 (SHA-256 fuzz, Dart rounding), not by
// this package. Columns: (phase, reps, ease, intervalDays, dueDay, lapses,
// firstSeenDay) after each run.
typedef Expected = (String, int, double, int, String?, int, String?);

const key = 'a1b2c3d4e5f60718';

final class Step {
  const new(this.run, this.expected);
  final RunRecord run;
  final Expected expected;
}

var _n = 0;

Step _step(
  RunMode mode,
  String day,
  double creditSum, {
  required Expected expect,
  bool completed = true,
  bool deviated = false,
  int graded = 10,
}) => Step(
  scoredRun(
    id: 'r${_n++}',
    lineKey: key,
    mode: mode,
    day: day,
    finishedAt: _n,
    creditSum: creditSum,
    graded: graded,
    completed: completed,
    deviated: deviated,
  ),
  expect,
);

Expected actual(SrsState s) => (
  s.phase.dbValue,
  s.reps,
  s.ease,
  s.intervalDays,
  s.dueDay,
  s.lapses,
  s.firstSeenDay,
);

void main() {
  final scenarios = <String, List<Step>>{
    'S01 perfect reviews on their due days': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-15',
        10,
        expect: ('review', 3, 2.80, 12, '2026-01-27', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-27',
        10,
        expect: ('review', 4, 2.90, 35, '2026-03-03', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-03-03',
        10,
        expect: ('review', 5, 3.00, 107, '2026-06-18', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-06-18',
        10,
        expect: ('review', 6, 3.00, 180, '2026-12-15', 0, '2026-01-10'),
      ),
    ],
    'S02 passing at 95 % keeps the ease': [
      _step(
        RunMode.srs,
        '2026-01-10',
        9.5,
        expect: ('review', 1, 2.50, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        9.5,
        expect: ('review', 2, 2.50, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-15',
        9.5,
        expect: ('review', 3, 2.50, 11, '2026-01-26', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-26',
        9.5,
        expect: ('review', 4, 2.50, 29, '2026-02-24', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-02-24',
        9.5,
        expect: ('review', 5, 2.50, 77, '2026-05-12', 0, '2026-01-10'),
      ),
    ],
    'S03 90 % passes, 85 % fails a first review': [
      _step(
        RunMode.srs,
        '2026-01-10',
        9,
        expect: ('review', 1, 2.50, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        8.5,
        expect: ('learning', 0, 2.30, 0, '2026-01-11', 1, '2026-01-10'),
      ),
    ],
    'S04 a failed first review is relearned the same day': [
      _step(
        RunMode.srs,
        '2026-01-10',
        5,
        expect: ('learning', 0, 2.30, 0, '2026-01-10', 1, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.40, 1, '2026-01-11', 1, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.50, 4, '2026-01-15', 1, '2026-01-10'),
      ),
    ],
    'S05 a lapse in review resets reps and costs ease': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-15',
        10,
        expect: ('review', 3, 2.80, 12, '2026-01-27', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-27',
        7,
        expect: ('learning', 0, 2.60, 0, '2026-01-27', 1, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-27',
        10,
        expect: ('review', 1, 2.70, 1, '2026-01-28', 1, '2026-01-10'),
      ),
    ],
    'S06 an early pass changes nothing': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-12',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
    ],
    'S07 an early failure lapses': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-12',
        6,
        expect: ('learning', 0, 2.50, 0, '2026-01-12', 1, '2026-01-10'),
      ),
    ],
    'S08 failures outside SRS pull the due date': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.random,
        '2026-01-12',
        9,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.random,
        '2026-01-12',
        8,
        expect: ('review', 2, 2.70, 4, '2026-01-12', 0, '2026-01-10'),
      ),
      _step(
        RunMode.weak,
        '2026-01-11',
        2,
        expect: ('review', 2, 2.70, 4, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 3, 2.80, 12, '2026-01-23', 0, '2026-01-10'),
      ),
    ],
    'S09 the interval is capped at 180 days': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-15',
        10,
        expect: ('review', 3, 2.80, 12, '2026-01-27', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-27',
        10,
        expect: ('review', 4, 2.90, 35, '2026-03-03', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-03-03',
        10,
        expect: ('review', 5, 3.00, 107, '2026-06-18', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-06-18',
        10,
        expect: ('review', 6, 3.00, 180, '2026-12-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-12-15',
        10,
        expect: ('review', 7, 3.00, 180, '2027-06-13', 0, '2026-01-10'),
      ),
    ],
    'S10 ease never drops below 1.3': [
      _step(
        RunMode.srs,
        '2026-01-10',
        0,
        expect: ('learning', 0, 2.30, 0, '2026-01-10', 1, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        1,
        expect: ('learning', 0, 2.10, 0, '2026-01-10', 2, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        1,
        expect: ('learning', 0, 1.90, 0, '2026-01-10', 3, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        1,
        expect: ('learning', 0, 1.70, 0, '2026-01-10', 4, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        1,
        expect: ('learning', 0, 1.50, 0, '2026-01-10', 5, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        1,
        expect: ('learning', 0, 1.30, 0, '2026-01-10', 6, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        1,
        expect: ('learning', 0, 1.30, 0, '2026-01-10', 7, '2026-01-10'),
      ),
    ],
    'S11 ease never rises above 3.0': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-15',
        10,
        expect: ('review', 3, 2.80, 12, '2026-01-27', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-27',
        10,
        expect: ('review', 4, 2.90, 35, '2026-03-03', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-03-03',
        10,
        expect: ('review', 5, 3.00, 107, '2026-06-18', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-06-18',
        10,
        expect: ('review', 6, 3.00, 180, '2026-12-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-12-15',
        10,
        expect: ('review', 7, 3.00, 180, '2027-06-13', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2027-06-13',
        10,
        expect: ('review', 8, 3.00, 180, '2027-12-10', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2027-12-10',
        10,
        expect: ('review', 9, 3.00, 180, '2028-06-07', 0, '2026-01-10'),
      ),
    ],
    'S12 abandoned, deviated and ungraded SRS runs are ignored': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        0,
        completed: false,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        5,
        deviated: true,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        0,
        graded: 0,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
    ],
    'S13 a single-line drill failure pulls the due date': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.single,
        '2026-01-13',
        8,
        expect: ('review', 2, 2.70, 4, '2026-01-13', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-13',
        10,
        expect: ('review', 3, 2.80, 12, '2026-01-25', 0, '2026-01-10'),
      ),
    ],
    'S14 a late review schedules from the day it happens': [
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.60, 1, '2026-01-11', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-11',
        10,
        expect: ('review', 2, 2.70, 4, '2026-01-15', 0, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-02-09',
        10,
        expect: ('review', 3, 2.80, 12, '2026-02-21', 0, '2026-01-10'),
      ),
    ],
    'S15 failures outside SRS do not touch new or learning lines': [
      _step(
        RunMode.random,
        '2026-01-10',
        0,
        expect: ('new', 0, 2.50, 0, null, 0, null),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        4,
        expect: ('learning', 0, 2.30, 0, '2026-01-10', 1, '2026-01-10'),
      ),
      _step(
        RunMode.random,
        '2026-01-10',
        0,
        expect: ('learning', 0, 2.30, 0, '2026-01-10', 1, '2026-01-10'),
      ),
      _step(
        RunMode.srs,
        '2026-01-10',
        10,
        expect: ('review', 1, 2.40, 1, '2026-01-11', 1, '2026-01-10'),
      ),
    ],
  };

  group('SRS scenarios', () {
    scenarios.forEach((name, steps) {
      test(name, () {
        var s = SrsState.initial;
        for (final (i, step) in steps.indexed) {
          s = applySrsRun(s, step.run, key);
          expect(actual(s), step.expected, reason: 'after run ${i + 1}');
        }
        expect(replaySrs(key, [for (final st in steps) st.run]), s);
      });
    });
  });

  test('there are at least 12 scenarios', () {
    expect(scenarios.length, greaterThanOrEqualTo(12));
  });
}
